### ISSUE TITLE
possibility of having custom properties of the model nodes

### ISSUE THREAD

**Issue by volodymyrss** [threeML/threeML#228]
what is the best way to characterize nodes sources with some properties, such as source name, time at which this model applies, or even energy range (though the last one can be dealt with by providing a global model, this might be a bit unnatural)

(maybe this belongs to astromodels, but maybe it is easier to keep together, as it relates to the fitting.)

**Comment by giacomov** [comment]
Regarding the name, each node has a `name` property.

For the rest, I think informations such as the cut on the data (energy and time) do not belong to the source, but to the data, so they should be properties of the plugins, not of the sources.

A model can be a function of time, but only in the sense that parameters can be made varying with time using auxiliary variables.

Does this answer your question?

If there is a need for more metadata to belong to a model, we could implement a `.metadata` dictionary which can contain arbitrary metadata.

**Comment by volodymyrss** [comment]
I thought properties like this might belong both to the source and to the data, albeit with rather different meaning (which is why I made two separate issues). The case with the data is clear.

The case with the model is more complex.

The "name" property seems highly restrictive, it can not be a common source name, for example. E.g. "1A 0535+262" is not a valid name for 3 separate reasons, (even "Cyg X-1" is not good enough), I have need to encode it and keep track of the bijection. Actually, this is a pretty big problem in many cases using astromodels. (maybe I am not using it right?)

For the rest, the case of the time-dependent model is a good example. Can I make a time-dependent model which consists of several constant episodes, distant from each other? The source may evolve pretty dramatically, at some stage, there is no point in inventing global models apart from piece-wise constant parameters. I guess it could be part of one source with such a specific time-dependent model.

But, at what point we preserve the concept of identify of the source, in a sense of consistent historical perspective?
Is a physical object in a given neighborhood a fixed named source identify? Or a new knot, responsible for a flare is a new source?
I want to have a flexible way to identify the source, so that reflect both the relation to the named object, e.g. "Crab nebula", and a particular phenomenon, characterized (at least at first) primarily by its time (e.g. flux enhancement of 2009).
The model structure may change as the understanding improves, but at many points, it seems unavoidable.
Complexity of the source identity can not be reduced to a python-identified-compatible string 50 characters long. Well, with some effort, it can be, by encoding (which is what I do now and this is dumb).

**Comment by giacomov** [comment]
@volodymyrss every choice we make has good and bad consequences. We decided very early on that we wanted to be able to address parameters and sources in astromodels as in:

`model.source.spectrum.main.powerlaw.index`

instead of:

`model['source']['spectrum']['main']['powerlaw']['index']`

to avoid going crazy with all the parenthesis and quotes, and to be able to speed up the access with a C++ ad-hoc class (the Node class).

This has the consequence of restricting the name of things to identifiers that are legal names for a python variable (think how this would be interpreted by python: `model.Cyg X-1.spectrum.main.powerlaw.index`). So yes, names must be encoded and decoded. I had to solve this problem myself in the 3FGL Fermi catalog (threeML/catalogs/Fermi.py):

```python
def _sanitize_3fgl_name(fgl_name):
    swap = fgl_name.replace(" ", "_").replace("+", "p").replace("-", "m").replace(".", "d")

    if swap[0] in ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']:
        swap = "_%s" % swap

    return swap
```

One way to deal with this would be to introduce an encoder/decoder for IAU names somewhere in 3ML so we can reuse it from different plugins.

Regarding the other point, if you have a source that varies dramatically with time and you do not want to model the time variability using parameters, but you have simply "step functions" then you can use a collection of models instead of one model. There is no way around this, because a source could very well change spectral shape during two different stages, and how can you represent this in an easy way?

So if you have two unrelated episodes for the same source, you should probably have two different models, which you can save into different files (`crab_nebula_2009_flare.yml` and `crab_nebula_normal_state.yml`). 

If you want something more fancy, we could think about a model container where models are indexed as dictionary keys, that can be serialized and deserialized to disk, something like:

```python
container = ModelContainer("crab")
container['2009 flare'] = model1
container['steady flux'] = model2
container.write_to("crab_container.yml")
new_container = ModelContainer.read_from("crab_container.yml")
```

**Comment by volodymyrss** [comment]
It can be solved also by keeping real source name in the node metadata. 

The episodes might not be completely unrelated, I want to load two at once, try different models. First maybe link some parameters. Then maybe make a global evolution model.
But I need to start somewhere.
Can I keep some parameters evolving with time, and leave others adjust to each spectrum independently? Seems to be a common scientific use case.

Currently there is already one thing treated in this way - constant, one per spectrum. Identified by name.
I basically followed this path (where there was no way to make a real global model) and ended up with very long parameter names, essentially encoded from metadata. Because I wanted to avoid this, this issue was created.

**Comment by grburgess** [comment]
Yup, I've made a solution for this too. So it will come soon

**Comment by giacomov** [comment]
@grburgess can you lay out the proposed solution before implementing it?

I am sorry I keep putting brakes on you, but you tend to "shut up and code", which although a normal approach for in-house code, it's not how it is supposed to be in a shared large project... ;-)

I need you to lay out your plan, discuss with us consequences (which might not be apparent to you) and then when we agreed you (or we) can code it up.

**Comment by grburgess** [comment]
@giacomov this was a push from a long time ago: #115  We put in tags to set external properties and included a way to quickly create a model that had common parameters free, fixed or linking in time. But this still needs some work as it only addresses models that do not need to be integrated over time.

**Comment by grburgess** [comment]
Is this issue solved?
