### ISSUE TITLE
strategic: aggregation vs specialization and dependency

### ISSUE THREAD

**Issue by volodymyrss** [threeML/threeML#230]
It's a generic question. 
I need some features specific for INTEGRAL. E.g. ability to read special responses and spectra. I could have continued to suggest updates to 3ML, but instead, for now, I did it separately, i.e. I inherit and keep  the plugins (and a bunch of other classes) in a separate project. This is faster to do.
What is, in your opinion, the way to proceed: fragmenting and specializing, or adding to 3ML master?

**Comment by grburgess** [comment]
@volodymyrss I did the same for my GBM response generator:

https://github.com/grburgess/trigdat_reader/blob/master/trigdat_reader/balrog_like.py

I think this plugin could be generalized because other instruments may want to generate responses on the fly and the method is general... just need a generic response generator class that is a place holder. 


Other than that, I think we need to have an in-depth meeting on a lot of these issues so that our own projects don't vary too much from the core goal. It would be nice to list features we need, things we are capable of implementing, and what features are generic enough to put in as standard. 

I'm on US time starting Wednesday night, but I would be up for some Skype conference with @giacomov and yourself so that we can align our work. There are a lot more people using... and I'm blind to the HAWC side of things.

**Comment by volodymyrss** [comment]
But if you follow this approach, why keep any plugins inside 3ml? why not keep only the non-instrument specific prototypes. 

So can you propose an agenda to what exactly to discuss? The list of the items.

**Comment by grburgess** [comment]
I think that is the idea... you can make your own things if needed, but we standardize common things.

**Comment by giacomov** [comment]
Having a meeting is a good idea.

Regarding the question in the subject, in general you do not want the user to have to install several packages each one with a plugin.

At the same time, I think it is reasonable to have plugins requiring a substantial amount of code specific to the instrument (like the one @grburgess mentioned) in their own repository.

In general my preference is to have things below an arbitrary complexity threshold within the repository.

In a way, this is what is already happening with HAWC and Fermi: the core of the software is actually in external packages, and the plugin is just an interface.

**Comment by volodymyrss** [comment]
For me, most of the software is of course outside.
The question is really whether the plugins should be even inside. So that the core contains only the highly extensible interface. But that's a matter of preference really, I see your point.

Why do I need to install HAWC and Fermi plugins if I am going to analyse only INTEGRAL and XRT?..
The question is also of a organizational nature: there can be different external implementations (e.g. more extensible calibration-level, simplified user-level, etc) of INTEGRAL plugins, it's easier to develop them  separately and test. 
But, in principle, once in a while a version of the plugins can be adopted to the 3ML all-in-one pack.

**Comment by grburgess** [comment]
@volodymyrss I think that is just it. You can have custom low-level versions locally if you desire, and if you need a custom plugin for normal analysis that is beyond the scope of the basic, XY, Spectrum, etc plugins, then you could push an interface-style or full working-style plugin for that instrument. I suppose the purpose of pushing custom instrument plugins in to the main branch in these cases depends on if you want many users to be able to fit the data. 

I would not mind pushing some of my custom parts, but I am not sure that they are really needed to do GBM analysis at the moment.
