### ISSUE TITLE
fixing build tests

### ISSUE THREAD

**Issue by grburgess** [threeML/threeML#319]
The tests are currently failing except for the cron builds. It appears to be some version mismatch in conda with pytest and setuptools. I'm currently trying different things, but at a loss for how the system works.

**Comment by giacomov** [comment]
I'll have a look. Keep in mind that the Cron job does not try to build 3ML for conda, that's why it doesn't fail. It only tries to run tests.

Right now it looks like the culprit is a missing package in `conda-forge` (the `toolchain`). I think we can do without (it was supposed to set some of the env variables), so I have removed it for the moment, let's see if it helps.

**Comment by giacomov** [comment]
I'm trying to fix the situation right now, but there are a few points that will need to be fixed pretty soon (although not immediately):

- tests: the new pytest broke compatibility with our tests by disallowing the direct all of fixtures. It is an easy fix, but it needs to be done. See https://docs.pytest.org/en/latest/deprecations.html#calling-fixtures-directly
-Some of the conda packages like `xspec-modelsonly` will sooner or later need to be rebuild in the new `conda-forge` system. Instead of using the `toolchain` package they will need to use the compilers package: https://anaconda.org/conda-forge/compilers

**Comment by grburgess** [comment]
Alright. I can take a look at those issues to learn. 

/J. Michael

**Comment by giacomov** [comment]
The tests pass now, I fixed them for the moment.

For the future, maybe we should move away from conda and make things easier to reduce the amount of maintenance that this part of the workflow need.

After all, 3ML, astromodels and all accompanying things are pure python.

The only problematic pieces are `xspec` and `ROOT`, but we could move the responsibility for those to the user. If the user installs the Fermi ST or HAWC software he will get `root` anyway. 

It remains the question of `xspec`. At the moment our cross section there is the `xspec-modelsonly` package which I created to distribute xspec models without the need to install the entire heasoft, which is very difficult to do in the same environment of the Fermi ST and the HAWC software. We can keep providing that separately, it does not change often.

@grburgess @omodei let me know your thoughts.

**Comment by grburgess** [comment]
If you are suggesting to move away from Conda for the tests... I agree. We can probably achieve things with a docker easily. The Conda build is amazing with fermi tools In a docker i use for LAT analysis. We should discuss this in detail via Skype. I can hopefully recruit some help at pygamma for handling Conda. It’s just outside my expertise.
