### ISSUE TITLE
How to build pha, bak and rsp files via TimeSeriesBuilder?

### ISSUE THREAD

**Issue by Tangqingwen** [threeML/threeML#364]
Hi!
In the section of "Example joint fit between GBM and Swift BAT", pha, bak and rsp files are needed, but I do not know how to build it by TimeSeriesBuilder?  How to produce them, for example to GBM data and LAT data? 
When I use the original cspec file, rsp files, and a bak file from rmfit for a detector, it can be read, but the following processes seems to be wrong. For example, .view_count_spectrum() does not work.

Thanks so much!

**Comment by grburgess** [comment]
Hello,

There is documentation for the time series builder here: https://threeml.readthedocs.io/en/latest/notebooks/Building_Plugins_from_TimeSeries.html

Please let us know if there is further explanation required.

Currently, LAT data must be produced (reduced) via the Fermi Science Tools as is the case for many other instruments. In fact, the design of 3ML is to not use LAT data (other than) in the form of PHA files as this reduces the sensitivity of the instrument. 

As for the issue with view count spectrum, please provide example code and full error output so that we can assess the problem.

**Comment by Tangqingwen** [comment]
Hi J. Michael Burgess,
Your comments solved my problems exactly!

 Thank you very much.

**Comment by grburgess** [comment]
However, the view count spectrum is not working?

**Comment by Tangqingwen** [comment]
> However, the view count spectrum is not working?

When loading the data derived from  the time series builder, the view count spectrum now does work. 

Thank you!
