### ISSUE TITLE
Help with threeML fit

### ISSUE THREAD

**Issue by mishaulan** [threeML/threeML#365]
I"m trying to fit FermiLat data over a period from to  .  When I use a power law fit I get an index that is close to the published 3FHL and 4FGL values, but fitting with a log-parabola doesn't return the values I'd expect.  I've tried running with parameters in a narrow bound around the expected values and also with wider parameter bounds but in both cases the a large number of events are thrown out of the fit, and the fitted parameter values are far off those I'd expect.  The same happens when I ran over the original 3FHL timerange.
Any Suggestions?

My code is attached.  Here's the fit values returned.

WARNING UserWarning: 24.46 percent of samples have been thrown away because they                                                                                                              failed the constraints on the parameters. This results might not be suitable fo                                                                                                             r error propagation. Enlarge the boundaries until you loose less than 1 percent                                                                                                              of the samples.
Best fit values:
                                                            result  \
parameter
Mrk421.spectrum.main.Log_parabola.K      (10.0 -1.6 +1.9) x 10^-17
Mrk421.spectrum.main.Log_parabola.alpha             -1.46 +/- 0.34
Mrk421.spectrum.main.Log_parabola.beta           (6 +/- 4) x 10^-1
                                                    unit
parameter
Mrk421.spectrum.main.Log_parabola.K      1 / (cm2 keV s)
Mrk421.spectrum.main.Log_parabola.alpha
Mrk421.spectrum.main.Log_parabola.beta
Correlation matrix:
col0 col1 col2
---- ---- ----
1.00 0.31 0.63
0.31 1.00 0.70
0.63 0.70 1.00
Values of -log(likelihood) at the minimum:
       -log(likelihood)
LAT          628.104422
total        628.104422

[fermi_mkn421_3mlHAl.txt](https://github.com/threeML/threeML/files/5017626/fermi_mkn421_3mlHAl.txt)

**Comment by omodei** [comment]
I am trying to replicate your example. I am having trouble downloading LAT data using the download_LAT_data method. Now I am downloading the data manually. Can you check meanwhile that you have LAT data covering the entire dates selection?

**Comment by omodei** [comment]
I have downloaded manually the LAT data (you can connect to the url that is shown when you run your script (look for this output in the terminal:)

"If this download fails, you can find your data at https://fermi.gsfc.nasa.gov/cgi-bin/ssc/LAT/QueryResults.cgi?id=L20080314454820F6A8B354 (when ready)"
You'll have to download the files manually (wget is not working, I have report this to the FSSC...)

Once I have downloaded the files, I have created a file containing the list of ft1:
ls L20080314454820F6A8B354_PH0* > list.txt
Then I merged the files using:
gtselect list.txt
(You should select the whole sky (Ra,Dec = 0,0 ROI=180, xmax=180, everything else 0)
Then change your script so that:
evfile, scfile = 'ft1.fits','ft2.fits'
where ft1.fits is the merged ft1 file (from the previous step, and ft2.fits is the name of the FT2 file you downloaded).

This is what I got:

WARNING UserWarning: 7.92 percent of samples have been thrown away because they failed the constraints on the parameters. This results might not be suitable for error propagation. Enlarge the boundaries until you loose less than 1 percent of the samples.

Best fit values:
result  \
parameter                                                           
Mrk421.spectrum.main.Log_parabola.K      (1.22 +/- 0.07) x 10^-16   
Mrk421.spectrum.main.Log_parabola.alpha            -1.70 +/- 0.10   
Mrk421.spectrum.main.Log_parabola.beta      (1.7 +/- 1.2) x 10^-1   

                                                    unit  
parameter                                                 
Mrk421.spectrum.main.Log_parabola.K      1 / (cm2 keV s)  
Mrk421.spectrum.main.Log_parabola.alpha                   
Mrk421.spectrum.main.Log_parabola.beta                    

Correlation matrix:

col0 col1 col2
---- ---- ----
1.00 0.37 0.66
0.37 1.00 0.72
0.66 0.72 1.00

Values of -log(likelihood) at the minimum:

       -log(likelihood)
LAT         6117.159265
total       6117.159265

Values of statistical measures:

     statistical measures
AIC          12232.318529
BIC          12234.318529

So the result is definitely different from yours. Also, I have noticed that your minimum energy is 10 GeV, which is, in my opinion, too high if you want to constrain the log-parabola. Can you try this procedure, and then usig emin=100 (MeV)

**Comment by omodei** [comment]
This is also related to issue  #356

**Comment by mishaulan** [comment]
I've been using an emin of 10 GeV because I'm trying to use the same general parameters as the 3FHL.  I did however take your suggestion and ran with emin=100 MeV which returns a fit of:
WARNING UserWarning: 50.82 percent of samples have been thrown away because they failed the constraints on the parameters. This results might not be suitable for error propagation. Enlarge the boundaries until you loose less than 1 percent of the samples.

Best fit values:

                                                                result  \
parameter
Mrk421.spectrum.main.Log_parabola.K           (6.4 -0.5 +0.6) x 10^-17
Mrk421.spectrum.main.Log_parabola.alpha               -2.014 +/- 0.025
Mrk421.spectrum.main.Log_parabola.beta   (2.00000 +/- 0.00026) x 10^-2

Correlation matrix:

col0 col1 col2
---- ---- ----
1.00 0.94 0.00
0.94 1.00 0.00
0.00 0.00 1.00

Values of -log(likelihood) at the minimum:

       -log(likelihood)
LAT        92830.558069
total      92830.558069

Values of statistical measures:

     statistical measures
AIC         185659.116138
BIC         185661.116138
