### ISSUE TITLE
Joint spectral analysis of Fermi GBM and LAT 

### ISSUE THREAD

**Issue by rahulc157** [threeML/threeML#370]
Hi,

I created GBM and LAT spectra using gtburst software. I am able to plugin GBM and LAT LLE spectra but not to LAT high energy spectrum. How to plugin the Fermi-LAT data of GRBs in threeML? 

Also while fitting time-resolved spectra, I noticed negative BIC values in some of the bins, what could be a possible reason?

Thank you.

**Comment by grburgess** [comment]
1) First thing to note, I would ignore BIC and AIC values in general, but very much so BIC. We place them there out of convenience, but BIC is not really something one should use for any reason. Moreover, only relative values of any point statistic matters. 

2) Gtburst is great software, but we have placed a lot of the functionality into 3ML (much of it coming from gtburst which was written by the authors of 3ML). I would check out this part in the [documentation](https://threeml.readthedocs.io/en/latest/notebooks/Building_Plugins_from_TimeSeries.html#Constructing-time-series-objects-from-different-data-types). The idea is that it will stream line your analysis so that you will not have to move back and forth between gtburst and 3ML for GBM and LLE data. You can easily rebin in time, etc.

3) For the LAT data, you will have to be more specific. There is FermiLATLike which is a plugin that needs to be updated, but it is more geared towards transient analysis. We are looking to make the process of obtaining transient data from the LAT easier and more integrated into 3ML as well, but it will rely on GtBurst under the hood. For now, you would need to make this data with GtBurst and then read those files into the FermiLATLike. We are sorely missing documentation on this process, so I will key in @omodei and @ndilalla to help further

**Comment by rahulc157** [comment]
Thank you very much @grburgess . I agree with suggestion on BIC, however I find negative value of  -log(likelihood) as well. How to explain this?

I tried to plugin Fermi LAT data using FermiLATLike  but got the following error.


File "/home/rahul/anaconda3/envs/threeML/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-6-a5051932b5ed>", line 13, in <module>
    LAT = FermipyLike( "LAT", eventFile, ft2File, ltcube, 'unbinned', expomap )

  File "/home/rahul/anaconda3/envs/threeML/lib/python3.7/site-packages/threeML/plugins/FermipyLike.py", line 233, in __new__
    _expensive_imports_hook()

  File "/home/rahul/anaconda3/envs/threeML/lib/python3.7/site-packages/threeML/plugins/FermipyLike.py", line 214, in _expensive_imports_hook
    from fermipy.gtanalysis import GTAnalysis

  File "/home/rahul/anaconda3/envs/threeML/lib/python3.7/site-packages/fermipy/__init__.py", line 15, in <module>
    import pyLikelihood

  File "/home/rahul/ScienceTools-v11r5p3-fssc-20180124-x86_64-unknown-linux-gnu-libc2.26/x86_64-unknown-linux-gnu-libc2.26/lib/python/pyLikelihood.py", line 34
    raise AttributeError,name
                        ^
SyntaxError: invalid syntax

**Comment by grburgess** [comment]
you will need to install the fermi tools to use the fermi plugin. Also, the fermi told currently only work with python2 until NASA upgrades to python3 which would be in the near future.

**Comment by rahulc157** [comment]
Hi,

Thanks @grburgess .

I have two quires, one related to temporal (LC) and other related to spectral plotting in flux unit along with data.

1. Can we get the energy-resolved prompt emission light curve (in different energy bins) of Fermi GBM/LAT-LLE data using 3ML? Like we can get the full energy channel LC following below but how to select the energy bins for LC?
 https://threeml.readthedocs.io/en/latest/notebooks/Building_Plugins_from_TimeSeries.html . 

2. i am able to plot fitted spectra output in model space (in flux unit) using following line (see below), can we plot this along with data sets as well?

 fig = plot_spectra(jl_eac.results,ene_min=1, ene_max=1e4, fit_colors='blue', contour_colors='blue', num_ene=1000, contour_style_kwargs=dict(alpha=0.1),flux_unit='keV/(cm2 s)')

**Comment by grburgess** [comment]
Hi @rahulc157 

1) this ability does not exist in 3ML at the time, but would be a welcome contribution.

2) Do you mean plotting the data simultaneously in flux space?

**Comment by rahulc157** [comment]
Thanks @grburgess .

1. i find some where, it was there (to set energy resolution for LC) earlier in threeML, it is an important aspect. Hope it will be included soon.
2. Yes, I want to plot data and model both in \nu F_{\nu} space, something like Figure 2 from this paper https://arxiv.org/pdf/1811.05433.pdf .

**Comment by grburgess** [comment]
@rahulc157 We explicitly do not plot data points in flux space because there is no correct way to do that. Though it appears in many publications, it is an incorrect thing to do. 

I have seen that people used 3ML to do this, but it was done in a custom way and we do not recommend it.
